# Generated by Django 4.2.17 on 2025-01-10 10:35

from django.db import migrations, models
import django.db.models.deletion
from datetime import time


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='bookings.court')),
            ],
        ),
    ]

def create_default_availability(apps, schema_editor):
    Court = apps.get_model('bookings', 'Court')
    Availability = apps.get_model('bookings', 'Availability')

    courts = Court.objects.all()
    for court in courts:
        # Monday to Saturday: 8am-10pm
        for day in range(6):  # Monday to Saturday (0-5)
            Availability.objects.create(
                court=court,
                day_of_week=day,
                start_time=time(8, 0),
                end_time=time(22, 0)
            )
        # Sunday: 8am-8pm
        Availability.objects.create(
            court=court,
            day_of_week=6,  # Sunday (6)
            start_time=time(8, 0),
            end_time=time(20, 0)
        )

class Migration(migrations.Migration):
    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_availability),
    ]
