# Generated by Django 4.2.17 on 2025-01-12 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_availability_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
