# Generated by Django 4.2.17 on 2025-01-14 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_availability_day_of_week_availability_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='booked_by',
        ),
        migrations.AddField(
            model_name='booking',
            name='availability',
            field=models.ForeignKey(default=460, on_delete=django.db.models.deletion.CASCADE, to='bookings.availability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default="2025-01-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(),
        ),
    ]
