# Generated by Django 4.2.17 on 2025-01-14 13:25

from django.db import migrations
from datetime import timedelta

def populate_availability(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    Availability = apps.get_model('bookings', 'Availability')

    for booking in Booking.objects.all():
        try:
            availability = Availability.objects.get(
                court=booking.court,
                date=booking.booking_date,
                start_time=booking.booking_time
            )
            booking.availability = availability
            booking.save()
        except Availability.DoesNotExist:
            print(f"No Availability found for Booking ID: {booking.id}, Court: {booking.court}, Date: {booking.booking_date}, Time: {booking.booking_time}")
            booking.delete() #Deletes booking if no availabilty is found
        except Exception as e:
            print(f"An unexpected error occurred for Booking ID: {booking.id}. Error: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20250114_1207'),
    ]

    operations = [
        migrations.RunPython(populate_availability),
    ]
